### ISSUE TITLE
Update access control

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-authz#25]
access control needs to be updated to allow grants data to be read by all logged in users.

according to this document https://docs.google.com/document/d/1xSAVSfjM_49CMdL3uqlSHcc5hg9g63Vxq916qqqatMc/edit

**Comment by karenhanson** [comment]
@htpvu I believe this has now been resolved by #28

**Comment by birkland** [comment]
Yes, this issue has been addressed in #28.  The user roles document, however, is out of date, and will be made even more so by the proxy use case.
