### ISSUE TITLE
Cut a new release and resulting image 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-authz#76]
Cute a new release and produce new image of this components as part of the resolution for this ticket https://github.com/OA-PASS/general-issues/issues/68

**Comment by birkland** [comment]
Release tagged https://github.com/OA-PASS/pass-authz/tree/0.4.2
Image published https://github.com/OA-PASS/pass-docker/commit/dbb24f54e5efec8ee3fcf521a8c32dc20d2e5151
